all:
	#nim c -d:debug --gc=orc -d=mingw --app=console --cpu=amd64 tests.nim
	nim c -d:debug --gc=orc -d=mingw --app=console --cpu=amd64 execute_powershell.nim
	cp execute_powershell.exe /home/msc/documents/tmp
clean:
	rm execute_powershell.exe



