token-stomping:
	nim c -d:debug --gc=orc -d=mingw --app=console --cpu=amd64 token_stomping.nim
	mv token_stomping.exe ../../bin/ttps
keylogger:
	nim c -d:debug --gc=orc -d=mingw --app=console --cpu=amd64 keylogger.nim
	mv keylogger.exe ../../bin/ttps
minidump:
	nim c -d:debug --gc=orc -d=mingw --app=console --cpu=amd64 minidump.nim
	mv minidump.exe ../../bin/ttps
dpapi:
	nim c -d:debug --gc=orc -d=mingw --app=console --cpu=amd64 dpapi_chrome.nim
	mv dpapi_chrome.exe ../../bin/ttps
ppid:
	nim c -d:debug --gc=orc -d=mingw --app=console --cpu=amd64 ppid_spoofing.nim
	mv ppid_spoofing.exe ../../bin/ttps
process_hollow:
	nim c -d:debug --gc=orc -d=mingw --app=console --cpu=amd64 process_hollowing.nim
	mv process_hollowing.exe ../../bin/ttps
powershell:
	nim c --gc=orc -d=mingw --app=console --cpu=amd64 exec_powershell.nim
	mv exec_powershell.exe ../../bin/ttps
wmi:
	nim c -d:debug --gc=orc -d=mingw --app=console --cpu=amd64 wmi_enumeration.nim
	mv wmi_enumeration.exe ../../bin/ttps
inject:
	nim c -d:debug --gc=orc -d=mingw --app=console --cpu=amd64 inject_via_crt.nim
	mv inject_via_crt.exe ../../bin/ttps
shellcode:
	nim c -d:debug --gc=orc -d=mingw --app=console --cpu=amd64 execute_shellcode.nim
	mv execute_shellcode.exe ../../bin/ttps
firewall:
	nim c -d:debug --gc=orc -d=mingw --app=console --cpu=amd64 block_mcafee_firewall.nim
	mv block_mcafee_firewall.exe ../../bin/ttps
schtask:
	nim c -d:debug --gc=orc -d=mingw --app=console --cpu=amd64 scheduled_tasks.nim
	mv scheduled_tasks.exe ../../bin/ttps
admin:
	nim c -d:debug --gc=orc -d=mingw --app=console --cpu=amd64 createLocalAdmin.nim
	mv createLocalAdmin.exe ../../bin/ttps
registry:
	nim c -d:debug --gc=orc -d=mingw --app=console --cpu=amd64 registryRunFolder.nim
	mv registryRunFolder.exe ../../bin/ttps
token:
	nim c -d:debug --gc=orc -d=mingw --app=console --cpu=amd64 steal_token.nim
	mv steal_token.exe ../../bin/ttps
service:
	nim c -d:debug --gc=orc -d=mingw --app=console --cpu=amd64 createService.nim
	mv createService.exe ../../bin/ttps
